package com.financesystem.finance_api.modules.governance.notifications.domain.model;

public enum NotificationType {
    TRANSFER_RECEIVED,
    TRANSFER_SENT,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    DEPOSIT_CONFIRMED,
    WITHDRAWAL_CONFIRMED,
    REFUND_COMPLETED,
    REVERSAL_COMPLETED,
    QR_CONFIRMED,
    ACCOUNT_BLOCKED,
    ACCOUNT_APPROVED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_FROZEN,
    ACCOUNT_CLOSED,
    LOGIN_ALERT,
    SECURITY_ALERT,
    SYSTEM_NOTICE,
    LIMIT_REVIEW_REQUIRED,
    LIMIT_EXCEEDED,
    FX_RATE_UPDATED,
    FEE_UPDATED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED
}
