services:
  serv-db:
    image: postgres:16
    container_name: finance_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - serv_pg_data:/var/lib/postgresql/data
    networks:
      - finance-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  serv-api:
    build:
      context: ./finance-api
      dockerfile: Dockerfile.dev
    container_name: finance_api
    restart: unless-stopped
    depends_on:
      serv-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DB_HOST: serv-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      TENANT_HEADER_NAME: ${TENANT_HEADER_NAME}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./finance-api:/app
      - maven_cache:/root/.m2
    working_dir: /app
    command: sh -c "sed -i 's/\r$//' ./mvnw && chmod +x ./mvnw && ./mvnw clean spring-boot:run"
    networks:
      - finance-net

  serv-web:
    build:
      context: ./finance-web
      dockerfile: Dockerfile.dev
    container_name: finance_web
    restart: unless-stopped
    depends_on:
      - serv-api
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./finance-web:/app
      - web_node_modules:/app/node_modules
    working_dir: /app
    command: npm start
    networks:
      - finance-net

volumes:
  serv_pg_data:
  maven_cache:
  web_node_modules:

networks:
  finance-net:
