package com.financesystem.finance_api.modules.tenant.reporting.domain.model.transactions;

public enum TransactionReportGroupByKey {
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    TRANSACTION_CHANNEL,
    TRANSACTION_CURRENCY,
    TRANSACTION_SOURCE_ACCOUNT_NUMBER,
    TRANSACTION_SOURCE_ACCOUNT_DISPLAY_NAME,
    TRANSACTION_TARGET_ACCOUNT_NUMBER,
    TRANSACTION_TARGET_ACCOUNT_DISPLAY_NAME,
    TRANSACTION_REQUESTED_BY_USER_EMAIL,
    TRANSACTION_REQUESTED_BY_USER_FULL_NAME,
    TRANSACTION_APPROVED_BY_USER_EMAIL,
    TRANSACTION_APPROVED_BY_USER_FULL_NAME
}
