package com.financesystem.finance_api.modules.tenant.reporting.domain.model.transactions;

public enum TransactionReportColumnKey {
    TRANSACTION_ID,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    TRANSACTION_CHANNEL,
    TRANSACTION_AMOUNT,
    TRANSACTION_CURRENCY,
    TRANSACTION_SOURCE_ACCOUNT_NUMBER,
    TRANSACTION_SOURCE_ACCOUNT_DISPLAY_NAME,
    TRANSACTION_TARGET_ACCOUNT_NUMBER,
    TRANSACTION_TARGET_ACCOUNT_DISPLAY_NAME,
    TRANSACTION_EXTERNAL_REFERENCE,
    TRANSACTION_IDEMPOTENCY_KEY,
    TRANSACTION_DESCRIPTION,
    TRANSACTION_FAILURE_REASON,
    TRANSACTION_REQUESTED_BY_USER_EMAIL,
    TRANSACTION_REQUESTED_BY_USER_FULL_NAME,
    TRANSACTION_APPROVED_BY_USER_EMAIL,
    TRANSACTION_APPROVED_BY_USER_FULL_NAME,
    TRANSACTION_PROCESSED_AT,
    TRANSACTION_CREATED_AT,
    TRANSACTION_UPDATED_AT
}
