# HTTP -> HTTPS
server {
    listen 80;
    server_name sebaces.fyi;

    return 301 https://$host$request_uri;
}

# HTTPS REAL
server {
    listen 443 ssl;
    http2 on;

    server_name sebaces.fyi;

    ssl_certificate /etc/letsencrypt/live/sebaces.fyi/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sebaces.fyi/privkey.pem;

    client_max_body_size 20M;

    location / {
        proxy_pass http://serv-finance-web:80;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://serv-finance-api:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /flutter/ {
        proxy_pass http://serv-finance-flutter-web:80/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# server {
#     listen 80;
#     #es dinamico y no requiere ip-server
#     server_name _;

#     client_max_body_size 20M;

#     location / {
#         proxy_pass http://serv-finance-web:80;
#         proxy_http_version 1.1;

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }

#     location /api/ {
#         proxy_pass http://serv-finance-api:8080;
#         proxy_http_version 1.1;

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }

#     location /flutter/ {
#         proxy_pass http://serv-finance-flutter-web:80/;  # !Importante¡ trailing slash (/) 

#         proxy_http_version 1.1;

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }