package com.financesystem.finance_api.modules.tenant.reporting.domain.model.transactionmovements;

public enum TransactionMovementReportFieldKey {
    MOVEMENT_ID,
    MOVEMENT_TRANSACTION_ID,
    MOVEMENT_TRANSACTION_TYPE,
    MOVEMENT_TRANSACTION_STATUS,
    MOVEMENT_TRANSACTION_CHANNEL,
    MOVEMENT_TRANSACTION_AMOUNT,
    MOVEMENT_TRANSACTION_CURRENCY,
    MOVEMENT_TRANSACTION_CREATED_AT,
    MOVEMENT_ACCOUNT_ID,
    MOVEMENT_ACCOUNT_NUMBER,
    MOVEMENT_ACCOUNT_NAME,
    MOVEMENT_ACCOUNT_DISPLAY_NAME,
    MOVEMENT_TYPE,
    MOVEMENT_AMOUNT,
    MOVEMENT_CURRENCY,
    MOVEMENT_BALANCE_BEFORE,
    MOVEMENT_BALANCE_AFTER,
    MOVEMENT_DESCRIPTION,
    MOVEMENT_CREATED_AT
}
